language: java
jdk:
  - oraclejdk8

before_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git checkout master'

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew createRelease'
  - ./gradlew assemble
  - ./gradlew check

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git config --global user.email "builds@travis-ci.com" && git config --global user.name "Travis CI" && git push -q --tags https://$GITHUB_OAUTH_TOKEN@github.com/tobilarscheid/jaxrs-etag-filter > /dev/null 2>&1'

branches:
  except:
    - /^v-*/
