language: java
jdk:
  - oraclejdk8

before_script:
  - git checkout master

script:
  - ./gradlew createRelease
  - ./gradlew assemble
  - ./gradlew check

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git push -q --tags

branches:
  except:
    - /^v-*/
